CREATE TABLE "MetersAsColumns" (
	id INTEGER NOT NULL, 
	datetime TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	"A71 Mitchell Hospital (B1)" FLOAT NOT NULL, 
	"A06 Crerar Library (B1)" FLOAT NOT NULL, 
	"F02 Steam Plant (B1)" FLOAT NOT NULL, 
	"G02 Capin Hall (B1)" FLOAT NOT NULL, 
	"D36 Social Science Building (B1)" FLOAT NOT NULL, 
	"A75 DCAM (R1)" FLOAT NOT NULL, 
	"A75 DCAM (R2)" FLOAT NOT NULL, 
	"H01 Computers 1155 Building (B1)" FLOAT NOT NULL, 
	"A11 Kovler Laboratories (B1)" FLOAT NOT NULL, 
	"A08 Hinds Laboratories (R1)" FLOAT NOT NULL, 
	"A75 DCAM (R3)" FLOAT NOT NULL, 
	"A84 American School (B1)" FLOAT NOT NULL, 
	"A62 Cummings Life Sciences (B1)" FLOAT NOT NULL, 
	"A13 Bookstore (B1)" FLOAT NOT NULL, 
	"H02 Law School (B1)" FLOAT NOT NULL, 
	"A22 Carlson Animal Research (B4)" FLOAT NOT NULL, 
	"F02 Steam Plant (B2)" FLOAT NOT NULL, 
	"C02 Crown Field House (B1)" FLOAT NOT NULL, 
	"E21 Breckinridge House (B1)" FLOAT NOT NULL, 
	"A27 Chicago Lying Hospital (B1)" FLOAT NOT NULL, 
	"A14 Brain Research Pavilion (B1)" FLOAT NOT NULL, 
	"D14 Center Gender Studies (B1)" FLOAT NOT NULL, 
	"L07 5482 S. Greenwood Ave (R1)" FLOAT NOT NULL, 
	"A23 Billings Hospital (B1)" FLOAT NOT NULL, 
	"A17 Wyler Child Hospital (B1)" FLOAT NOT NULL, 
	"D25 Walker Museum (R1)" FLOAT NOT NULL, 
	"D25 Walker Museum (R2)" FLOAT NOT NULL, 
	"I13 Woodlawn Social Service (B1)" FLOAT NOT NULL, 
	"A16 Peck Pavilion (B1)" FLOAT NOT NULL, 
	"D53 Pick Hall (R1)" FLOAT NOT NULL, 
	"N11 ATS (B1)" FLOAT NOT NULL, 
	"B34 Stagg Field Building (B1)" FLOAT NOT NULL, 
	"D16 Eckhart/Ryerson (B1)" FLOAT NOT NULL, 
	"D16 Eckhart/Ryerson (B2)" FLOAT NOT NULL, 
	"C31 54th & Ellis Parking (B1)" FLOAT NOT NULL, 
	"C31 54th & Ellis Parking (B2)" FLOAT NOT NULL, 
	"D20 Levi Hall (B1)" FLOAT NOT NULL, 
	"I10 6022-24 S. Drexel (B3)" FLOAT NOT NULL, 
	"B36 BSLC (B1)" FLOAT NOT NULL, 
	"A50 MRS Building (CLSC) (B1)" FLOAT NOT NULL, 
	"F02 Steam Plant (B3)" FLOAT NOT NULL, 
	"E44 Booth Harper Center (B1)" FLOAT NOT NULL, 
	"E44 Booth Harper Center (B2)" FLOAT NOT NULL, 
	"E44 Booth Harper Center (B3)" FLOAT NOT NULL, 
	"E44 Booth Harper Center (B4)" FLOAT NOT NULL, 
	"B34 Stagg Field Building (B2)" FLOAT NOT NULL, 
	"L07 5482 S. Greenwood Ave (R2)" FLOAT NOT NULL, 
	"A16 Peck Pavilion (B2)" FLOAT NOT NULL, 
	"D37 Stuart Hall (B1)" FLOAT NOT NULL, 
	"D06 Anatomy Building (R1)" FLOAT NOT NULL, 
	"G03 NGRH (B2)" FLOAT NOT NULL, 
	"A12 Ingleside Hall (B1)" FLOAT NOT NULL, 
	"C36 Alumni House (R1)" FLOAT NOT NULL, 
	"D54 Special Events (B1)" FLOAT NOT NULL, 
	"F10 1537 E. 60th Parking (R1)" FLOAT NOT NULL, 
	"A19 Franklin Institute (B2)" FLOAT NOT NULL, 
	"A07 Kersten Physics (R1)" FLOAT NOT NULL, 
	"D06 Anatomy Building (B1)" FLOAT NOT NULL, 
	"A87 Comer's Child Hospital (R4)" FLOAT NOT NULL, 
	"A87 Comer's Child Hospital (R5)" FLOAT NOT NULL, 
	"B34 Stagg Field Building (B5)" FLOAT NOT NULL, 
	"B36 BSLC (R3)" FLOAT NOT NULL, 
	"A87 Comer's Child Hospital (R6)" FLOAT NOT NULL, 
	"G14 Kimbark Parking Lot (R1)" FLOAT NOT NULL, 
	"C02 Crown Field House (R3)" FLOAT NOT NULL, 
	"I02 Midway Studios (U1)" FLOAT NOT NULL, 
	"F12 Press Building (B1)" FLOAT NOT NULL, 
	"G01 Orthogenic School (R1)" FLOAT NOT NULL, 
	"H02 Law School (B2)" FLOAT NOT NULL, 
	"A22 Carlson Animal Research (B3)" FLOAT NOT NULL, 
	"A15 Abbott Memorial Hall (R1)" FLOAT NOT NULL, 
	"A14 Brain Research Pavilion (R4)" FLOAT NOT NULL, 
	"H09 6031 S. Ellis (R1)" FLOAT NOT NULL, 
	"H09 6031 S. Ellis (R2)" FLOAT NOT NULL, 
	"H01 Computers 1155 Building (R1)" FLOAT NOT NULL, 
	"A75 DCAM (R4)" FLOAT NOT NULL, 
	"E21 Breckinridge House (B2)" FLOAT NOT NULL, 
	"H03 6025 S. Ellis (B)" FLOAT NOT NULL, 
	"A18 Armour Research (B1)" FLOAT NOT NULL, 
	"A16 Peck Pavilion (B3)" FLOAT NOT NULL, 
	"A16 Peck Pavilion (B4)" FLOAT NOT NULL, 
	"A62 Cummings Life Sciences (B3)" FLOAT NOT NULL, 
	"E52 McGiffert (B1)" FLOAT NOT NULL, 
	"B98 KCBD (R1)" FLOAT NOT NULL, 
	"B98 KCBD (R2)" FLOAT NOT NULL, 
	"B98 KCBD (R3)" FLOAT NOT NULL, 
	"D47 Development II (B1)" FLOAT NOT NULL, 
	"E01 Robie House (B2)" FLOAT NOT NULL, 
	"F15 6035 S. Blackstone (B1)" FLOAT NOT NULL, 
	"F15 6035 S. Blackstone (B2)" FLOAT NOT NULL, 
	"F15 6035 S. Blackstone (B4)" FLOAT NOT NULL, 
	"E13 International House (B1)" FLOAT NOT NULL, 
	"C36 Alumni House (B2)" FLOAT NOT NULL, 
	"D20 Levi Hall (R1)" FLOAT NOT NULL, 
	"D46 Human Development (R1)" FLOAT NOT NULL, 
	"A07 Kersten Physics (B4)" FLOAT NOT NULL, 
	"H01 1155 Building (U2)" FLOAT NOT NULL, 
	"A86 GCIS (B6)" FLOAT NOT NULL, 
	"B113 5615 S. Maryland (B1)" FLOAT NOT NULL, 
	"B113 5615 S. Maryland (B2)" FLOAT NOT NULL, 
	"B113 5615 S. Maryland (B3)" FLOAT NOT NULL, 
	"B113 5615 S. Maryland (B4)" FLOAT NOT NULL, 
	"A23 Billings Hospital (B2)" FLOAT NOT NULL, 
	"A86 GCIS (B7)" FLOAT NOT NULL, 
	"H09 6031 S. Ellis (B1)" FLOAT NOT NULL, 
	"A62 Cummings Life Sciences (B5)" FLOAT NOT NULL, 
	"A07 Kersten Physics (B2)" FLOAT NOT NULL, 
	"D19 Jones Laboratory (B1)" FLOAT NOT NULL, 
	"A70 UC Hospital Chiller (B1)" FLOAT NOT NULL, 
	"A70 UC Hospital Chiller (B2)" FLOAT NOT NULL, 
	"D20 Levi Hall (B2)" FLOAT NOT NULL, 
	"C33 Max Palevsky Halls (B1)" FLOAT NOT NULL, 
	"A07 Kersten Physics (B3)" FLOAT NOT NULL, 
	"D07/D08 Snell-Hitchcock (B2)" FLOAT NOT NULL, 
	"H02 Law School (B3)" FLOAT NOT NULL, 
	"D19 Jones S/B Searle (B2)" FLOAT NOT NULL, 
	"D13 Math-Stat Building (B2)" FLOAT NOT NULL, 
	"B36 BSLC (U1)" FLOAT NOT NULL, 
	"A22 Carlson Animal Research (B2)" FLOAT NOT NULL, 
	"A08 Hinds Laboratories (B2)" FLOAT NOT NULL, 
	"D13 Math-Stat Building (B1)" FLOAT NOT NULL, 
	"B01 LASR (B1)" FLOAT NOT NULL, 
	"I29 61st & Drexel (B1)" FLOAT NOT NULL, 
	"H09 6025 S. Ellis Dining (B1)" FLOAT NOT NULL, 
	"E05 Lillie House (B1)" FLOAT NOT NULL, 
	"E20 Wilder House (B1)" FLOAT NOT NULL, 
	"B29 Univ. Service Garage (B1)" FLOAT NOT NULL, 
	"D54 Special Events (B2)" FLOAT NOT NULL, 
	"G01 Orthogenic School (B2)" FLOAT NOT NULL, 
	"D29 Rockefeller Chapel (B1)" FLOAT NOT NULL, 
	"D19 Jones S/B Searle (B1)" FLOAT NOT NULL, 
	"I10 6022-24 S. Drexel (B2)" FLOAT NOT NULL, 
	"D48 5737 S. University Ave (U1)" FLOAT NOT NULL, 
	"B27 5631-33 S. Maryland (B1)" FLOAT NOT NULL, 
	"A62 Cummings Life Sciences (B4)" FLOAT NOT NULL, 
	"NHP CCD (B1)" FLOAT NOT NULL, 
	"NHP (B1)" FLOAT NOT NULL, 
	"NHP (B2)" FLOAT NOT NULL, 
	"C25 Mansueto (B1)" FLOAT NOT NULL, 
	"C25 Mansueto (B2)" FLOAT NOT NULL, 
	"NHP (B3)" FLOAT NOT NULL, 
	"NHP (B4)" FLOAT NOT NULL, 
	"NHP (B5)" FLOAT NOT NULL, 
	"NHP (B6)" FLOAT NOT NULL, 
	"NHP (B7)" FLOAT NOT NULL, 
	"NHP (B8)" FLOAT NOT NULL, 
	"NHP (B9)" FLOAT NOT NULL, 
	"NHP (B10)" FLOAT NOT NULL, 
	"NHP (B11)" FLOAT NOT NULL, 
	"NHP (B12)" FLOAT NOT NULL, 
	"NHP (B13)" FLOAT NOT NULL, 
	"C03 Regenstein Library (B1)" FLOAT NOT NULL, 
	"C03 Regenstein Chiller (B1)" FLOAT NOT NULL, 
	"D19 Jones Laboratory (B2)" FLOAT NOT NULL, 
	"G10 Atomic Scientists (B3)" FLOAT NOT NULL, 
	"B36 BSLC (B2)" FLOAT NOT NULL, 
	"H03 Burton Judson (B1)" FLOAT NOT NULL, 
	"D45 Press Journals (B2)" FLOAT NOT NULL, 
	"E13 International House (B2)" FLOAT NOT NULL, 
	"I29 61st & Drexel (B2)" FLOAT NOT NULL, 
	"C25 Mansueto (B3)" FLOAT NOT NULL, 
	"A08 Hinds Laboratories (B1)" FLOAT NOT NULL, 
	"F15 6035 S. Blackstone (B3)" FLOAT NOT NULL, 
	"D01 Quadrangle Club (B3)" FLOAT NOT NULL, 
	"A62 Cummings Life Sciences (B6)" FLOAT NOT NULL, 
	"CTS - New 1407 E 60th (B1)" FLOAT NOT NULL, 
	"DLAC (B1)" FLOAT NOT NULL, 
	"D45 Press Journals (U1)" FLOAT NOT NULL, 
	"D01 Quadrangle Club (B2)" FLOAT NOT NULL, 
	"DLAC (B2)" FLOAT NOT NULL, 
	"DLAC (B3)" FLOAT NOT NULL, 
	"CTS - New 1407 E 60th (B2)" FLOAT NOT NULL, 
	"E01 Robie House (B3)" FLOAT NOT NULL, 
	"D18 Kent Laboratory (B1)" FLOAT NOT NULL, 
	"DLAC (B4)" FLOAT NOT NULL, 
	"A87 Comer's Child Hospital (B6)" FLOAT NOT NULL, 
	"A87 Comer's Child Hospital (B7)" FLOAT NOT NULL, 
	"A87 Comer's Child Hospital (B8)" FLOAT NOT NULL, 
	"A87 Comer's Child Hospital (B9)" FLOAT NOT NULL, 
	"A86 GCIS (B8)" FLOAT NOT NULL, 
	"G10 Atomic Scientists (B2)" FLOAT NOT NULL, 
	"A86 GCIS (B9)" FLOAT NOT NULL, 
	"A86 GCIS (B10)" FLOAT NOT NULL, 
	"A86 GCIS (B11)" FLOAT NOT NULL, 
	"A86 GCIS (B12)" FLOAT NOT NULL, 
	"D10 Culver Hall (B2)" FLOAT NOT NULL, 
	"E52 McGiffert (U1)" FLOAT NOT NULL, 
	"B03 Accelerator Building (B1)" FLOAT NOT NULL, 
	"B03 Accelerator Building (B2)" FLOAT NOT NULL, 
	"E09 Ida Noyes Hall (B2)" FLOAT NOT NULL, 
	"D45 Press Journals (B3)" FLOAT NOT NULL, 
	"A70 UC Hospital Parking (B1)" FLOAT NOT NULL, 
	"G03 NGRH (B1)" FLOAT NOT NULL, 
	"E52 McGiffert (B2)" FLOAT NOT NULL, 
	"D69 1164-78 E. 58th Street (U1)" FLOAT NOT NULL, 
	"F08 Laboratory Services (U1)" FLOAT NOT NULL, 
	"E21 Breckinridge House (U1)" FLOAT NOT NULL, 
	"E44 Booth Harper Center (U1)" FLOAT NOT NULL, 
	"E44 Booth Harper Center (U2)" FLOAT NOT NULL, 
	"D29 Rockefeller Chapel (U1)" FLOAT NOT NULL, 
	"H02 Law School (U1)" FLOAT NOT NULL, 
	"D69 1164-78 E. 58th Street (B4)" FLOAT NOT NULL, 
	"D19 Jones Laboratory (U1)" FLOAT NOT NULL, 
	"A70 UC Hospital Parking (U1)" FLOAT NOT NULL, 
	"G03 NGRH (U1)" FLOAT NOT NULL, 
	"D53 Pick Hall (U2)" FLOAT NOT NULL, 
	"A25 Gilman Smith Hospital (U1)" FLOAT NOT NULL, 
	"A19 Franklin Institute (U1)" FLOAT NOT NULL, 
	"A19 Franklin Institute (U2)" FLOAT NOT NULL, 
	"D53 Pick Hall (U1)" FLOAT NOT NULL, 
	"D18 Kent Laboratory (U1)" FLOAT NOT NULL, 
	"A06 Crerar Library (U1)" FLOAT NOT NULL, 
	"D01 Quadrangle (U1)" FLOAT NOT NULL, 
	"H01 1155 Building (U4)" FLOAT NOT NULL, 
	"A17 Wyler Child Hospital (U1)" FLOAT NOT NULL, 
	"A14 Brain Research Pavilion (U1)" FLOAT NOT NULL, 
	"A87 Comer's Child Hospital (U2)" FLOAT NOT NULL, 
	"A86 GCIS (U1)" FLOAT NOT NULL, 
	"Brain Research Pavilion (U2)" FLOAT NOT NULL, 
	"B08 Bio-Psych (U1)" FLOAT NOT NULL, 
	"A87 Comer's Child Hospital (U3)" FLOAT NOT NULL, 
	"H01 1155 Building (U5)" FLOAT NOT NULL, 
	"A06 Crerar Library (U2)" FLOAT NOT NULL, 
	"F12 Press Building (U1)" FLOAT NOT NULL, 
	"A87 Comer's Child Hospital (U4)" FLOAT NOT NULL, 
	"I04 Edelstone Hall (U1)" FLOAT NOT NULL, 
	"A08 Hinds Laboratories (U1)" FLOAT NOT NULL, 
	"C13 Smart Museum (U1)" FLOAT NOT NULL, 
	"A14 Brain Research Pavilion (U3)" FLOAT NOT NULL, 
	"I02 Midway Studios (U2)" FLOAT NOT NULL, 
	"B36 BSLC (U3)" FLOAT NOT NULL, 
	"B01 LASR (R2)" FLOAT NOT NULL, 
	"B36 BSLC (U4)" FLOAT NOT NULL, 
	"H03 Burton Judson (U1)" FLOAT NOT NULL, 
	"D38 Harper Library (U3)" FLOAT NOT NULL, 
	"A17 Wyler Child Hospital (U2)" FLOAT NOT NULL, 
	"D69 Becker Friedman (B1)" FLOAT NOT NULL, 
	"N11 ATS (U1)" FLOAT NOT NULL, 
	"D38 Harper Library (U1)" FLOAT NOT NULL, 
	"D21 Cobb Hall (U1)" FLOAT NOT NULL, 
	"D36 Social Science Building (U1)" FLOAT NOT NULL, 
	"D38 Harper Library (U2)" FLOAT NOT NULL, 
	"D42 Goodspeed Hall (U1)" FLOAT NOT NULL, 
	"A16 Peck Pavilion (U1)" FLOAT NOT NULL, 
	"A71 Mitchell Hospital (U1)" FLOAT NOT NULL, 
	"A19 Franklin Institute (U3)" FLOAT NOT NULL, 
	"D14 Center Gender Studies (B2)" FLOAT NOT NULL, 
	"E11 High School (B1)" FLOAT NOT NULL, 
	"E52 MicGiffert House (B1)" FLOAT NOT NULL, 
	"E11 High Schol (B3)" FLOAT NOT NULL, 
	"E05 Lillie House (R1)" FLOAT NOT NULL, 
	"H01 1155 Building (U1)" FLOAT NOT NULL, 
	"A84 American School (B2)" FLOAT NOT NULL, 
	"H01 1155 Building (U3)" FLOAT NOT NULL, 
	"D45 Press Journals (R3)" FLOAT NOT NULL, 
	"D47 Development II (R2)" FLOAT NOT NULL, 
	"E11 High School (U1)" FLOAT NOT NULL, 
	"E11 High School (U2)" FLOAT NOT NULL, 
	"A27 Chicago Lying Hospital (U1)" FLOAT NOT NULL, 
	"C13 Smart Museum (U2)" FLOAT NOT NULL, 
	"H01 1155 Building (U6)" FLOAT NOT NULL, 
	"C02 Crown Field House (U1)" FLOAT NOT NULL, 
	"A87 Comer's Child Hospital (U1)" FLOAT NOT NULL, 
	"B36 BSLC (U2)" FLOAT NOT NULL, 
	"A75 DCAM (U1)" FLOAT NOT NULL, 
	"A08 Hinds Laboratories (U2)" FLOAT NOT NULL, 
	"F10 1537 E. 60th Parking (R2)" FLOAT NOT NULL, 
	"G14 Kimbark Parking Lot (R2)" FLOAT NOT NULL, 
	"E11 High School (B2)" FLOAT NOT NULL, 
	"D37 Stuart Hall (B2)" FLOAT NOT NULL, 
	"B07 Eckhardt Research (B1)" FLOAT NOT NULL, 
	"B07 Eckhardt Research (B2)" FLOAT NOT NULL, 
	"D53 Pick Hall (U3)" FLOAT NOT NULL, 
	"D36 Social Science Building (B2)" FLOAT NOT NULL, 
	"B07 Eckhardt Research (B3)" FLOAT NOT NULL, 
	"B07 Eckhardt Research (B4)" FLOAT NOT NULL, 
	"B07 Eckhardt Research (B5)" FLOAT NOT NULL, 
	"L07 5482 S. Greenwood (U1)" FLOAT NOT NULL, 
	"C36 Alumni House (R2)" FLOAT NOT NULL, 
	"G01 Orthogenic School (U1)" FLOAT NOT NULL, 
	"D25 Walker Museum (U1)" FLOAT NOT NULL, 
	"D25 Walker Museum (U2)" FLOAT NOT NULL, 
	"D06 Anatomy Building (U1)" FLOAT NOT NULL, 
	"A07 Kersten Physics (U1)" FLOAT NOT NULL, 
	"NHP CCD (B2)" FLOAT NOT NULL, 
	"A22 Carlson Animal Reserach (U1)" FLOAT NOT NULL, 
	"H01 Computers 1155 Building (U1)" FLOAT NOT NULL, 
	"A15 Abbott Memorial Hall (U1)" FLOAT NOT NULL, 
	"A87 Comer's Child Hospital (U5)" FLOAT NOT NULL, 
	"A14 Brain Research Pavilion (U4)" FLOAT NOT NULL, 
	"A87 Comer's Child Hospital (U6)" FLOAT NOT NULL, 
	"E11 Gordon Parks Art Wing (B1)" FLOAT NOT NULL, 
	"E11 Gordon Parks Art Wing (B2)" FLOAT NOT NULL, 
	"E11 Gordon Parks Art Wing (B3)" FLOAT NOT NULL, 
	"NHP 56th & Drexel (B1)" FLOAT NOT NULL, 
	"CCD vault location (B1)" FLOAT NOT NULL, 
	"CCD (Parking Lot) (U1)" FLOAT NOT NULL, 
	"D46 Human Development (U1)" FLOAT NOT NULL, 
	"Kimbark Parking Lot (G14)" FLOAT NOT NULL, 
	"C36 Alumni House (U1)" FLOAT NOT NULL, 
	"D45 Press Journals (U2)" FLOAT NOT NULL, 
	"D47 Development II (U1)" FLOAT NOT NULL, 
	"F10 1537 E. 60th Parking (U1)" FLOAT NOT NULL, 
	"E05 Lillie House (U1)" FLOAT NOT NULL, 
	"L07 5482 S. Greenwood Ave (L07)" FLOAT NOT NULL, 
	"A75 DCAM (U2)" FLOAT NOT NULL, 
	"A75 DCAM (U3)" FLOAT NOT NULL, 
	"A75 DCAM (U4)" FLOAT NOT NULL, 
	"B98 KCBD (U1)" FLOAT NOT NULL, 
	"B01 LASR (U1)" FLOAT NOT NULL, 
	"D20 Levi Hall (U1)" FLOAT NOT NULL
);
